name: Release
on:
  push:
    tags: ["*"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
          gpg-passphrase: RELEASES_GPG_PASSPHRASE
      - name: Set Maven Version
        run: mvn versions:set --batch-mode --file ./pom.xml --define newVersion="${APP_VERSION}"
        env:
          APP_VERSION: ${{ github.ref_name }}
      - name: Build & Deploy Artifact to ghcr
        run: mvn --batch-mode deploy -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          RELEASES_GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
