name: Snapshot
on:
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Extract Version
        run: >-
          APP_SHA=$(git rev-parse --short ${GITHUB_SHA});
          APP_REV=$(git rev-list --tags --max-count=1);
          APP_TAG=$(git describe --tags ${APP_REV} 2> /dev/null || echo 0.0.0);
          echo "APP_VERSION=${APP_TAG}-${APP_SHA}" >> ${GITHUB_ENV};
      - name: Set Maven Version
        run: mvn versions:set --batch-mode --file ./pom.xml --define newVersion="${APP_VERSION}-SNAPSHOT"
      - name: Build & Deploy Artifact to Nexus Repository
        run: mvn --batch-mode deploy -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
